# Generated by Django 4.1 on 2022-08-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departmant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deparment', models.CharField(max_length=255)),
                ('num_course', models.IntegerField()),
                ('num_teachers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('roll_number', models.IntegerField()),
                ('deparment', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('semester_num', models.IntegerField()),
            ],
        ),
    ]
